version: '3'

services:
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: bagzon@gmail.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - landings
    networks:
      - app-network
  landings:
    container_name: html
    build:
      context: ../
      dockerfile: $PWD/../bk-landings/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  letsencrypt:

networks:
  app-network:
    driver: bridge
